// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataValueInput = {
  device_id: number;
  temperature: number;
  humidity: number;
  co: number;
  alcohol: number;
  co2: number;
  toluen: number;
  nh4: number;
  aceton: number;
  lpg: number;
  ch4: number;
  aqi: number;
  aqi_label: string;
  gas_leak_label: string;
};
