// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Model = {
  id: number;
  device_id: bigint;
  device_name: string | null;
  device_location: string | null;
  registered: boolean;
};
