// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model as DeviceModel } from "./Device";

import type { Model } from "./DataValue";
export type DeviceStats = {
  device: DeviceModel;
  data: Array<Model>;
  latest_data: Model | null;
};
