// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Registration = {
  device_id: bigint;
  device_name: string;
  device_location: string;
};
